name: Security scan

on:
  push:
    branches: [dev]
  pull_request:
    branches: [main]

permissions:
  security-events: write
  actions: read
  contents: read

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Inicializar CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: javascript-typescript

      - name: Análisis de CodeQL
        uses: github/codeql-action/analyze@v4